### ISSUE TITLE
Backend exited with code 1

### ISSUE THREAD

**Issue by MelBourbon** [croesnick/toniebox-audio-match#17]
I get the following error. .env file is set up. Using Debian.
```
backend_1   | Traceback (most recent call last):
backend_1   |   File "app.py", line 29, in <module>
backend_1   |     tonie_cloud_api = TonieCloud(os.environ.get("TONIE_AUDIO_MATCH_USER"), os.environ.get("TONIE_AUDIO_MATCH_PASS"))
backend_1   |   File "/backend/toniecloud/client.py", line 30, in __init__
backend_1   |     self.session.acquire_token(username, password)
backend_1   |   File "/backend/toniecloud/session.py", line 15, in acquire_token
backend_1   |     self.token = self._acquire_token(username, password)
backend_1   |   File "/backend/toniecloud/session.py", line 20, in _acquire_token
backend_1   |     return req.json()["jwt"]
backend_1   | KeyError: 'jwt'
toniebox-audio-match_backend_1 exited with code 1
```

**Comment by croesnick** [comment]
Hey @MelBourbon :)

Please excuse my late reply. The issue you observed was caused by a change in the authentication mechanism of the toniecloud. On September 1st 2020, they enforced SSO -- an issue I stumbled into myself -> see #15.

Glad to tell you that it should be fixed in the current master. :) Let me know if it works for you now.
